### ISSUE TITLE
随行无法使用

### ISSUE THREAD

**Issue by isoulgh** [VersionZKP2356/Dell-G3-3579-OpenCore-Boot-File#1]
可以搜索到，但连接时显示32002错误，无法使用随行，请问有办法解决吗？

**Comment by VersionZKP2356** [comment]
我没有IPAD设备，所以没有使用过随行，抱歉

**Comment by isoulgh** [comment]
谢谢回复，我已经解决了这个问题。

**Comment by vmadhavan15** [comment]
will this EFI work for VENTURA. on the G3 3579 DELL laptop.
